version: "2"

networks:
  discordbotnet:
    external: false
services:
  node:
    image: "ghcr.io/thedmo/reactor_discord-bot:latest"
    user: "node"
    working_dir: /app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: always
    networks: 
      - discordbotnet