services:
  Reactor-Dev:
    image: "node:latest"
    user: "node"
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./Reactbot:/app
    restart: always
    command: ["sh", "-c", "npm install && npm start"]
